import { challengeMessage, verifyWalletProof } from './wallet-proof';
import { validateWorkoutSession } from './validation';
import { isAllowedOrigin, rateLimitAllowed, rateLimitKey } from './security';
export interface Env { DB: D1Database; ALLOWED_ORIGIN: string; }
export interface D1Result<T = Record<string, unknown>> { results: T[]; success: boolean; meta?: Record<string, unknown>; }
export interface D1Prepared { bind(...values: unknown[]): D1Prepared; first<T = Record<string, unknown>>(): Promise<T | null>; all<T = Record<string, unknown>>(): Promise<D1Result<T>>; run(): Promise<D1Result>; }
export interface D1Database { prepare(query: string): D1Prepared; }
const json = (body: unknown, status = 200, origin = '*') => new Response(JSON.stringify(body), {status, headers:{'content-type':'application/json','access-control-allow-origin':origin,'access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,OPTIONS'}});
const day = () => new Date().toISOString().slice(0,10); const id = () => crypto.randomUUID();
async function body(request: Request): Promise<Record<string, any>> { try { return await request.json(); } catch { return {}; } }
export default { async fetch(request: Request, env: Env): Promise<Response> { const origin = env.ALLOWED_ORIGIN || request.headers.get('origin') || '*'; if (request.method === 'OPTIONS') return json(null,204,origin); const url = new URL(request.url); try {
  const isWrite=['POST','PUT','PATCH','DELETE'].includes(request.method); if(isWrite && !isAllowedOrigin(request.headers.get('origin'),env.ALLOWED_ORIGIN)) return json({error:'Origin is not allowed.'},403,origin); if(isWrite){const key=rateLimitKey(request); const now=Date.now(); const record=await env.DB.prepare('SELECT window_start,request_count FROM rate_limits WHERE rate_key=?').bind(key).first<any>(); if(!rateLimitAllowed(record,now)) return json({error:'Too many requests. Try again shortly.'},429,origin); if(!record || now-record.window_start>=60000) await env.DB.prepare('INSERT OR REPLACE INTO rate_limits(rate_key,window_start,request_count) VALUES(?,?,1)').bind(key,now).run(); else await env.DB.prepare('UPDATE rate_limits SET request_count=request_count+1 WHERE rate_key=?').bind(key).run();}
  if (url.pathname === '/health') return json({ok:true},200,origin);
  if (url.pathname === '/api/pool' && request.method === 'GET') return json(await env.DB.prepare('SELECT item_id as id,type,label,amount,stock,cost_points as costPoints FROM pool ORDER BY cost_points').all(),200,origin);
  if (url.pathname === '/api/feed' && request.method === 'GET') return json(await env.DB.prepare('SELECT event_id, wallet, kind, label, created_at FROM feed ORDER BY created_at DESC LIMIT 50').all(),200,origin);
  if (url.pathname === '/api/history' && request.method === 'GET') { const wallet=url.searchParams.get('wallet'); if(!wallet) return json({error:'Wallet is required.'},400,origin); return json(await env.DB.prepare('SELECT receipt_id as receiptId, quest_id as questId, day_key as dayKey, points_awarded as pointsAwarded, created_at as createdAt FROM receipts WHERE wallet=? ORDER BY created_at DESC LIMIT 100').bind(wallet).all(),200,origin); }
  if (url.pathname === '/api/settings' && request.method === 'GET') { const wallet=url.searchParams.get('wallet'); if(!wallet) return json({error:'Wallet is required.'},400,origin); const account=await env.DB.prepare('SELECT step_goal as stepGoal FROM accounts WHERE wallet=?').bind(wallet).first<any>(); return json({stepGoal:Number(account?.stepGoal||6000)},200,origin); }
  if (url.pathname === '/api/settings' && request.method === 'PUT') { const input=await body(request); const stepGoal=Number(input.stepGoal); if(typeof input.wallet!=='string'||!Number.isInteger(stepGoal)||stepGoal<3000||stepGoal>12000) return json({error:'Step goal must be an integer between 3,000 and 12,000.'},400,origin); await env.DB.prepare('INSERT INTO accounts(wallet,step_goal) VALUES(?,?) ON CONFLICT(wallet) DO UPDATE SET step_goal=excluded.step_goal').bind(input.wallet,stepGoal).run(); return json({stepGoal},200,origin); }
  if (url.pathname === '/api/leaderboard' && request.method === 'GET') return json(await env.DB.prepare('SELECT wallet, SUM(points_awarded) as points, COUNT(*) as receipts FROM receipts GROUP BY wallet ORDER BY points DESC LIMIT 50').all(),200,origin);
  if (url.pathname === '/api/sessions' && request.method === 'POST') { const input=await body(request); if (!input.startedAt || !input.endedAt || input.payload===undefined) return json({error:'Incomplete session payload.'},400,origin); const validation=validateWorkoutSession(input); if(!validation.ok) return json({error:validation.error},400,origin); const sessionId=id(); const sessionHash=await hash(JSON.stringify(input)); await env.DB.prepare('INSERT INTO sessions(session_id,wallet,quest_type,quest_id,day_key,started_at,ended_at,duration_sec,payload_json,session_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(sessionId,input.wallet,input.questType,input.questId,day(),input.startedAt,input.endedAt,Number(input.durationSec),JSON.stringify(input.payload),sessionHash,new Date().toISOString()).run(); return json({sessionId,sessionHash},201,origin); }
  if (url.pathname === '/api/challenges' && request.method === 'POST') { const input=await body(request); const session=await env.DB.prepare('SELECT * FROM sessions WHERE session_id=? AND wallet=?').bind(input.sessionId,input.wallet).first<any>(); if (!session) return json({error:'Session not found.'},404,origin); const existing=await env.DB.prepare('SELECT receipt_id FROM receipts WHERE wallet=? AND quest_id=? AND day_key=?').bind(session.wallet,session.quest_id,session.day_key).first(); if(existing) return json({error:'Quest already verified today.'},409,origin); const open=await env.DB.prepare('SELECT COUNT(*) as count FROM challenges WHERE wallet=? AND used_at IS NULL AND expires_at>?').bind(session.wallet,Date.now()).first<any>(); if(Number(open?.count||0)>=5) return json({error:'Too many open challenges.'},429,origin); const challenge={challengeId:id(),wallet:session.wallet,sessionHash:session.session_hash,questId:session.quest_id,dayKey:session.day_key,nonce:id(),issuedAt:Date.now(),expiresAt:Date.now()+300000}; await env.DB.prepare('INSERT INTO challenges(challenge_id,wallet,session_hash,quest_id,day_key,nonce,issued_at,expires_at) VALUES(?,?,?,?,?,?,?,?)').bind(challenge.challengeId,challenge.wallet,challenge.sessionHash,challenge.questId,challenge.dayKey,challenge.nonce,challenge.issuedAt,challenge.expiresAt).run(); return json({...challenge,message:challengeMessage(challenge)},201,origin); }
  if (url.pathname === '/api/complete' && request.method === 'POST') { const input=await body(request); const challenge=await env.DB.prepare('SELECT * FROM challenges WHERE challenge_id=?').bind(input.challengeId).first<any>(); if (!challenge) return json({error:'Challenge not found.'},404,origin); if (challenge.used_at) return json({error:'Challenge already used.'},409,origin); const proof=verifyWalletProof({challenge:{challengeId:challenge.challenge_id,wallet:challenge.wallet,questId:challenge.quest_id,dayKey:challenge.day_key,sessionHash:challenge.session_hash,nonce:challenge.nonce,expiresAt:challenge.expires_at},wallet:input.wallet,publicKey:input.publicKey,signature:input.signature}); if(!proof.ok) return json({error:proof.error},400,origin); const receipt={receiptId:id(),points:challenge.quest_id.includes('circuit')?10:8}; const consumed=await env.DB.prepare('UPDATE challenges SET used_at=? WHERE challenge_id=? AND used_at IS NULL').bind(Date.now(),challenge.challenge_id).run(); if(consumed.meta?.changes===0) return json({error:'Challenge already used.'},409,origin); await env.DB.prepare('INSERT INTO receipts(receipt_id,wallet,quest_id,day_key,session_hash,challenge_id,signature,public_key,points_awarded,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(receipt.receiptId,challenge.wallet,challenge.quest_id,challenge.day_key,challenge.session_hash,challenge.challenge_id,input.signature,proof.publicKey,receipt.points,new Date().toISOString()).run(); await env.DB.prepare('INSERT INTO accounts(wallet,points_balance,last_quest_day) VALUES(?,?,?) ON CONFLICT(wallet) DO UPDATE SET points_balance=accounts.points_balance+excluded.points_balance,last_quest_day=excluded.last_quest_day').bind(challenge.wallet,receipt.points,challenge.day_key).run(); await env.DB.prepare('INSERT INTO feed(event_id,wallet,kind,label,receipt_id,created_at) VALUES(?,?,?,?,?,?)').bind(id(),challenge.wallet,'completion',challenge.quest_id,receipt.receiptId,new Date().toISOString()).run(); return json({receiptId:receipt.receiptId,pointsAwarded:receipt.points},201,origin); }
  if (url.pathname === '/api/claims' && request.method === 'POST') { const input=await body(request); if(!input.wallet || !input.itemId) return json({error:'Wallet and item are required.'},400,origin); const item=await env.DB.prepare('SELECT * FROM pool WHERE item_id=?').bind(input.itemId).first<any>(); const account=await env.DB.prepare('SELECT points_balance FROM accounts WHERE wallet=?').bind(input.wallet).first<any>(); if(!item) return json({error:'Pool item not found.'},404,origin); if(!account || account.points_balance < item.cost_points) return json({error:'Insufficient points.'},409,origin); if(item.stock < 1) return json({error:'Pool item is out of stock.'},409,origin); const updated=await env.DB.prepare('UPDATE accounts SET points_balance=points_balance-? WHERE wallet=? AND points_balance>=?').bind(item.cost_points,input.wallet,item.cost_points).run(); if(!updated.success) return json({error:'Could not reserve points.'},409,origin); const stocked=await env.DB.prepare('UPDATE pool SET stock=stock-1 WHERE item_id=? AND stock>0').bind(item.item_id).run(); if(!stocked.success) { await env.DB.prepare('UPDATE accounts SET points_balance=points_balance+? WHERE wallet=?').bind(item.cost_points,input.wallet).run(); return json({error:'Pool item is out of stock.'},409,origin); } const claimId=id(); const status=item.type==='nim'?'pending':'paid'; await env.DB.prepare('INSERT INTO claims(claim_id,wallet,item_id,status,created_at) VALUES(?,?,?,?,?)').bind(claimId,input.wallet,item.item_id,status,new Date().toISOString()).run(); await env.DB.prepare('INSERT INTO feed(event_id,wallet,kind,label,claim_id,created_at) VALUES(?,?,?,?,?,?)').bind(id(),input.wallet,'claim',item.label,claimId,new Date().toISOString()).run(); return json({claimId,status,label:item.label},201,origin); }
  return json({error:'Not found.'},404,origin);
 } catch (error) { console.error(error); return json({error:'Internal server error.'},500,origin); } } };
async function hash(value: string): Promise<string> { const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)); return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join(''); }
