import init, { Hash, PublicKey, Signature } from '@nimiq/core/web';
let nimiqReady: Promise<unknown> | undefined;
const ensureNimiq = () => (nimiqReady ??= init());
const encoder = new TextEncoder();
export function encodeNimiqSignedMessage(message: string): Uint8Array { const body = encoder.encode(message); const prefix = encoder.encode(`\x16Nimiq Signed Message:\n${body.byteLength}`); const payload = new Uint8Array(prefix.byteLength + body.byteLength); payload.set(prefix); payload.set(body, prefix.byteLength); return payload; }
const isHex = (value: unknown, length: number): value is string => typeof value === 'string' && value.length === length && /^[a-fA-F0-9]+$/.test(value);
export function challengeMessage(challenge: { challengeId: string; wallet: string; questId: string; dayKey: string; sessionHash: string; nonce: string; expiresAt: number }): string { return `FitProof completion\nchallenge=${challenge.challengeId}\nwallet=${challenge.wallet}\nquest=${challenge.questId}\nday=${challenge.dayKey}\nsession=${challenge.sessionHash}\nnonce=${challenge.nonce}\nexpires=${challenge.expiresAt}`; }
export async function verifyWalletProof(input: { challenge: { challengeId: string; wallet: string; questId: string; dayKey: string; sessionHash: string; nonce: string; expiresAt: number }; wallet: string; publicKey: string; signature: string; now?: number }): Promise<{ ok: true; publicKey: string } | { ok: false; error: string }> {
  const {challenge, wallet, publicKey, signature} = input; if (wallet !== challenge.wallet) return {ok:false,error:'Wallet does not match the signed challenge.'}; if ((input.now ?? Date.now()) > challenge.expiresAt) return {ok:false,error:'Challenge expired.'}; if (!isHex(publicKey,64) || !isHex(signature,128)) return {ok:false,error:'Public key or signature has an invalid format.'};
  try { await ensureNimiq(); const parsedKey = PublicKey.fromHex(publicKey); if (parsedKey.toAddress().toUserFriendlyAddress() !== wallet) return {ok:false,error:'Public key does not belong to this wallet.'}; const valid = parsedKey.verify(Signature.fromHex(signature), Hash.computeSha256(encodeNimiqSignedMessage(challengeMessage(challenge)))); return valid ? {ok:true,publicKey:parsedKey.toHex()} : {ok:false,error:'Wallet signature is invalid.'}; } catch { return {ok:false,error:'Wallet proof could not be verified.'}; }
}
