import type { Quest } from './domain';
const base = (import.meta.env.VITE_API_URL ?? '').replace(/\/$/, '');
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${base}${path}`, {headers:{'content-type':'application/json',...(init?.headers||{})}, ...init}); const payload=await response.json(); if(!response.ok) throw new Error(payload.error || 'Request failed'); return payload as T; }
export type ChallengeResponse = { challengeId:string; wallet:string; questId:string; dayKey:string; sessionHash:string; nonce:string; issuedAt:number; expiresAt:number; message:string };
export type CompletionResponse = { receiptId:string; pointsAwarded:number };
export async function createProof(quest: Quest, wallet: string, signature: (message:string)=>Promise<{publicKey:string;signature:string}>, workoutPayload?: unknown): Promise<CompletionResponse> { const now=new Date(); const session=await request<{sessionId:string;sessionHash:string}>('/api/sessions',{method:'POST',body:JSON.stringify({wallet,questType:quest.type,questId:quest.id,startedAt:new Date(now.getTime()-quest.durationMin*60_000).toISOString(),endedAt:now.toISOString(),durationSec:quest.durationMin*60,payload:workoutPayload ?? (quest.type==='circuit'?{rounds:2,exercises:quest.exercises?.map(exercise=>({id:exercise.id,sets:2,reps:exercise.reps??1}))}:{minutes:quest.durationMin})})}); const challenge=await request<ChallengeResponse>('/api/challenges',{method:'POST',body:JSON.stringify({sessionId:session.sessionId,wallet})}); const signed=await signature(challenge.message); return request<CompletionResponse>('/api/complete',{method:'POST',body:JSON.stringify({challengeId:challenge.challengeId,wallet,publicKey:signed.publicKey,signature:signed.signature})}); }
export const getPool = () => request('/api/pool'); export const getFeed = () => request('/api/feed'); export const getLeaderboard = () => request('/api/leaderboard');
export const getHistory = (wallet: string) => request<{results:Array<{receiptId:string;questId:string;dayKey:string;pointsAwarded:number;createdAt:string}>}>(`/api/history?wallet=${encodeURIComponent(wallet)}`);
export const createClaim = (wallet: string, itemId: string) => request<{claimId:string;status:string;label:string}>('/api/claims', {method:'POST', body:JSON.stringify({wallet,itemId})});

export const getSettings = (wallet: string) => request<{stepGoal:number}>(`/api/settings?wallet=${encodeURIComponent(wallet)}`);
export const updateSettings = (wallet: string, stepGoal: number) => request<{stepGoal:number}>('/api/settings', {method:'PUT', body:JSON.stringify({wallet,stepGoal})});
