import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { canCompleteQuest, formatTime, Quest, todayQuests } from './domain';
import { maskWallet, Receipt } from './proof';
import { claimReward, defaultPool } from './rewards';
import { createNimiqWallet, walletErrorCopy } from './wallet';
import { createClaim, createProof, getFeed, getHistory, getLeaderboard } from './api';
import { advanceCircuit, createCircuitState, StepDetector, haversineMeters } from './workout';
import './styles.css';

type View = 'today' | 'player' | 'done' | 'history' | 'board' | 'feed';
function App() {
  const [view, setView] = useState<View>('today');
  const [selected, setSelected] = useState<Quest | null>(null);
  const [level, setLevel] = useState<'beginner'|'regular'>('beginner');
  const [completed, setCompleted] = useState<string[]>([]);
  const [receipt, setReceipt] = useState<Receipt | null>(null);
  const [proofReceiptId, setProofReceiptId] = useState<string | null>(null);
  const [sessionPayload, setSessionPayload] = useState<unknown>(null);
  const [wallet, setWallet] = useState<string | null>(null); const [walletError, setWalletError] = useState<string | null>(null); const [walletClient] = useState(() => createNimiqWallet());
  const quests = todayQuests(level); const points = completed.reduce((total, id) => total + (id.includes('circuit') ? 10 : 8), 0);
  const start = (quest: Quest) => { setSelected(quest); setView('player'); };
  const finish = (payload?: unknown) => { if (!selected) return; setSessionPayload(payload ?? null); setCompleted((items) => [...new Set([...items, selected.id])]); setView('done'); };
  return <main className="app">
    <header className="topbar"><div className="brand"><span className="brand-mark">✦</span><span>FIT<span className="accent">PROOF</span></span></div><button className="wallet" onClick={async () => { setWalletError(null); try { setWallet(await walletClient.connect()); } catch (error) { const key = error instanceof Error ? error.message as keyof typeof walletErrorCopy : 'wallet-error'; setWalletError(walletErrorCopy[key] ?? walletErrorCopy['wallet-error']); } }}>{wallet ? `${wallet.slice(0, 6)}…` : 'Connect wallet'} <span>↗</span></button></header>
    {walletError && <div className="wallet-error" role="alert">{walletError}</div>}
    {view === 'today' && <><section className="hero"><p className="eyebrow">THURSDAY · SEPTEMBER 4</p><h1>Move with purpose.</h1><p className="muted">Your wallet signs that you completed this app quest.</p><div className="streak"><span className="flame">♨</span><div><strong>{completed.length ? 1 : 0} day streak</strong><small>{points} points earned today</small></div></div></section><section className="section-head"><div><p className="eyebrow">TODAY'S QUESTS</p><h2>Pick one to get moving</h2></div><span className="progress">{completed.length}/3</span></section><div className="quest-grid">{quests.map((quest) => <article className={`quest-card ${completed.includes(quest.id) ? 'complete' : ''}`} key={quest.id}><div className="quest-icon">{quest.type === 'circuit' ? '◈' : quest.type === 'move' ? '◒' : '⌁'}</div><div className="quest-copy"><span className="tag">{quest.type}</span><h3>{quest.title}</h3><p>{quest.subtitle}</p><div className="meta"><span>+{quest.points} pts</span><span>◷ {quest.durationMin} min</span></div></div><button className="card-action" onClick={() => start(quest)}>{completed.includes(quest.id) ? 'Done' : 'Start'} <span>→</span></button></article>)}</div><section className="pool"><div><p className="eyebrow">REWARD POOL</p><h2>Earn from what's stocked</h2><p className="muted">{defaultPool.map((item) => item.label).join(' · ')}. Pool stock changes without a client release.</p><button className="card-action" disabled={points < defaultPool[0].costPoints} onClick={async () => { if (!wallet) { setWalletError('Connect your Nimiq wallet before claiming.'); return; } try { const claim = await createClaim(wallet, defaultPool[0].id); alert(`${claim.label} claim ${claim.status}.`); } catch (error) { setWalletError(error instanceof Error ? error.message : 'Claim failed.'); } }}>Claim 2 NIM <span>→</span></button></div><span className="pool-badge">{points}/10<br/><small>points</small></span></section><nav className="bottom-nav"><button className="active" onClick={() => setView('today')}>Today</button><button onClick={() => setView('history')}>History</button><button onClick={() => setView('board')}>Board</button><button onClick={() => setView('feed')}>Feed</button></nav></>}
    {view === 'player' && selected && <Player quest={selected} onBack={() => setView('today')} onFinish={finish} />}
    {view === 'history' && <SocialView kind="history" wallet={wallet} onBack={() => setView('today')} />}
    {view === 'board' && <SocialView kind="board" wallet={wallet} onBack={() => setView('today')} />}
    {view === 'feed' && <SocialView kind="feed" wallet={wallet} onBack={() => setView('today')} />}
    {view === 'done' && selected && <section className="center-screen"><div className="success-mark">✓</div><p className="eyebrow">SESSION COMPLETE</p><h1>{proofReceiptId ? 'Proof signed.' : 'Nice work.'}</h1><p className="muted">{proofReceiptId ? `Receipt ${proofReceiptId.slice(0, 8)} is verified for ${maskWallet(wallet ?? '')}.` : 'Your session is saved locally. Prove it with a wallet signature to appear on the board and claim rewards.'}</p><div className="summary"><span>+{selected.points} points</span><span>Grade A</span></div>{!proofReceiptId && <button className="primary" onClick={async () => { setWalletError(null); try { const account = wallet ?? await walletClient.connect(); setWallet(account); const result = await createProof(selected, account, (message) => walletClient.sign(message), sessionPayload); setProofReceiptId(result.receiptId); } catch (error) { const key = error instanceof Error ? error.message as keyof typeof walletErrorCopy : 'wallet-error'; setWalletError(walletErrorCopy[key] ?? walletErrorCopy['wallet-error']); } }}>Prove it with wallet <span>→</span></button>}{walletError && <div className="wallet-error" role="alert">{walletError}</div>}<button className={proofReceiptId ? 'primary' : 'secondary'} onClick={() => { setReceipt(null); setProofReceiptId(null); setSessionPayload(null); setView('today'); }}>Back to today <span>→</span></button></section>}
    <footer>Bodyweight movement only · Not medical advice · <button onClick={() => setLevel(level === 'beginner' ? 'regular' : 'beginner')}>Level: {level}</button></footer>
  </main>;
}
function SocialView({kind,wallet,onBack}:{kind:'history'|'board'|'feed';wallet:string|null;onBack:()=>void}) { const [rows,setRows]=useState<any[]>([]); const [error,setError]=useState<string|null>(null); useEffect(()=>{(async()=>{try{const result=kind==='history'?(wallet?await getHistory(wallet):{results:[]}):kind==='board'?await getLeaderboard():await getFeed();setRows((result as any).results??[]);}catch(e){setError(e instanceof Error?e.message:'Could not load data.');}})();},[kind,wallet]); const title=kind==='history'?'My history':kind==='board'?'Leaderboard':'Activity feed'; return <section className="social"><button className="back" onClick={onBack}>← Today</button><div className="player-heading"><span className="tag">Verified only</span><h1>{title}</h1><p className="muted">{kind==='history'?'Your wallet-signed quest receipts.':kind==='board'?'Ranked by verified quest points.':'Recent verified movement from the community.'}</p></div>{error&&<div className="wallet-error" role="alert">{error}</div>}{!rows.length&&!error&&<div className="empty">No verified activity yet.<small>Complete a quest and sign the proof to appear here.</small></div>}<div className="social-list">{rows.map((row,index)=><article className="social-row" key={row.receiptId??row.event_id??index}><span className="social-rank">{kind==='board'?`#${index+1}`:'✦'}</span><div><strong>{row.wallet?`${row.wallet.slice(0,6)}…`:row.label??'Verified quest'}</strong><small>{row.questId??row.label??`${row.receipts??0} receipts · ${row.points??0} points`}</small></div><span className="social-points">{row.pointsAwarded??row.points??''}</span></article>)}</div></section>; }
function Player({ quest, onBack, onFinish }: {quest: Quest; onBack:()=>void; onFinish:(payload?:unknown)=>void}) {
  const [seconds, setSeconds] = useState(quest.durationMin * 60); const [running, setRunning] = useState(false); const [steps, setSteps] = useState(0); const [motionDenied, setMotionDenied] = useState(false); const [distance, setDistance] = useState(0); const [circuit, setCircuit] = useState(createCircuitState());
  const detector = React.useMemo(() => new StepDetector(), []);
  useEffect(() => { if (!running || seconds <= 0) return; const id = window.setInterval(() => setSeconds(s => Math.max(0, s - 1)), 1000); return () => window.clearInterval(id); }, [running, seconds]);
  useEffect(() => { if (quest.type !== 'steps') return; const onMotion = (event: DeviceMotionEvent) => { const a=event.accelerationIncludingGravity; if(a) setSteps(detector.sample({x:a.x||0,y:a.y||0,z:a.z||0,timestamp:Date.now()})); }; const request = async () => { try { const permission=(DeviceMotionEvent as typeof DeviceMotionEvent & {requestPermission?:()=>Promise<string>}).requestPermission; if(permission && await permission() !== 'granted') throw new Error('denied'); window.addEventListener('devicemotion',onMotion); } catch { setMotionDenied(true); } }; request(); return () => window.removeEventListener('devicemotion',onMotion); }, [quest.type, detector]);
  useEffect(() => { if (quest.type !== 'move' || !navigator.geolocation) return; let previous: GeolocationCoordinates|null=null; const watch=navigator.geolocation.watchPosition(position=>{if(previous) setDistance(d=>d+haversineMeters({lat:previous!.latitude,lon:previous!.longitude},{lat:position.coords.latitude,lon:position.coords.longitude})); previous=position.coords;},()=>undefined,{enableHighAccuracy:false,maximumAge:10000}); return () => navigator.geolocation.clearWatch(watch); }, [quest.type]);
  const isCircuit=quest.type==='circuit'; const complete=isCircuit ? circuit.complete : quest.type==='steps' ? (steps>=6000 || motionDenied ? seconds===0 : false) : seconds===0; const current=quest.exercises?.[circuit.exercise];
  const advance=()=>{if(!quest.exercises) return; setCircuit(state=>advanceCircuit(state,quest.exercises!,Date.now()));};
  const payload = isCircuit ? {rounds:2,exercises:quest.exercises?.map(exercise=>({id:exercise.id,sets:2,reps:exercise.reps??1}))} : quest.type==='steps' ? {mode:motionDenied?'timed-walk':'motion',steps,minutes:motionDenied?quest.durationMin:undefined} : {minutes:quest.durationMin,meters:distance};
  return <section className="player"><button className="back" onClick={onBack}>← Today</button><div className="player-heading"><span className="tag">{quest.type} quest</span><h1>{quest.title}</h1><p className="muted">{quest.subtitle}</p></div>{isCircuit ? <><div className="round-status"><span>ROUND {Math.min(circuit.round,2)} / 2</span><strong>{current?.name}</strong><small>{current?.target} · tap complete after each set</small></div><div className="exercise-list">{quest.exercises?.map((exercise,index)=><div className={`exercise ${index===circuit.exercise && !circuit.complete?'current':''} ${index<circuit.exercise || circuit.complete?'checked':''}`} key={exercise.id}><span className="exercise-number">0{index+1}</span><div><strong>{exercise.name}</strong><small>{exercise.target}</small></div><span>{index<circuit.exercise || circuit.complete?'✓':index===circuit.exercise?'→':''}</span></div>)}</div><div className="round-note">{circuit.restUntil && circuit.restUntil>Date.now() ? 'Rest 30 seconds before the next move.' : 'Complete each move once, then repeat for round two.'}</div></> : <div className="timer"><span>{quest.type==='steps' ? motionDenied ? 'Timed walk fallback' : `${steps.toLocaleString()} / 6,000 steps` : `${(distance/1000).toFixed(2)} km tracked`}</span><strong>{formatTime(seconds)}</strong><div className="timer-ring" style={{'--progress':`${(1-seconds/(quest.durationMin*60))*360}deg`} as React.CSSProperties}></div></div>}<button className="primary" onClick={()=>isCircuit ? (complete?onFinish(payload):advance()) : (complete?onFinish(payload):setRunning(!running))}>{complete?'Finish session':running?'Pause timer':isCircuit?'Complete set':quest.type==='steps'&&motionDenied?'Start timed walk':'Start timer'} <span>→</span></button><p className="honesty">{quest.type==='steps'&&motionDenied?'Motion permission was denied; timed walk fallback is active.':'No health data is collected. Your proof attests to completing this app session.'}</p></section>;
}
createRoot(document.getElementById('root')!).render(<App />);
